name: Nelson CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
       shell: cmd
    timeout-minutes: 30
    steps:
      - name: Download Nelson v0.5.5
        run: |
          $null = mkdir c:/install
          (new-object net.webclient).DownloadFile("https://github.com/Nelson-numerical-software/nelson/releases/download/v0.5.5/Nelson-0.5.5.1197-x86-64.exe", "C:\install\Nelson-x86-64.exe")
        shell: powershell

      - name: Install Nelson
        run: |
          C:/install/Nelson-x86-64.exe /SP- /SILENT /DIR="c:/install/Nelson"

      - name: check nelson
        run: |
          dir /s "c:/install/Nelson/"

      - uses: actions/checkout@v2

      - name: build module
        run: |
          set
          "c:/install/Nelson/bin/x64/nelson-cli" --noipc --quiet -e "run('%GITHUB_WORKSPACE%/builder.nls');quit"


